package src.lexer;

/**
 * TokenSpecificType 表示更具体的子类型
 */
public enum TokenSpecificType {
    // 基本类型
    TYPE_INT, TYPE_LONG, TYPE_FLOAT, TYPE_DOUBLE, TYPE_BOOLEAN, TYPE_CHAR, TYPE_BYTE, TYPE_SHORT,
    // 常量
    CONST_INT, CONST_FLOAT, CONST_CHAR, CONST_STRING, CONST_BOOL,
    // 运算符
    OP_PLUS, OP_MINUS, OP_MUL, OP_DIV, OP_MOD,
    OP_ASSIGN, OP_EQ, OP_NE, OP_LT, OP_LE, OP_GT, OP_GE,
    OP_AND, OP_OR, OP_NOT, OP_XOR, OP_SHL, OP_SHR, OP_USHR,
    OP_INC, OP_DEC, OP_AND_AND, OP_OR_OR,
    // 分隔符
    DEL_LPAREN, DEL_RPAREN, DEL_LBRACE, DEL_RBRACE,
    DEL_LBRACKET, DEL_RBRACKET, DEL_SEMICOLON, DEL_COMMA, DEL_DOT, DEL_COLON,
    // 关键字
    RES_IF, RES_ELSE, RES_FOR, RES_WHILE, RES_DO, RES_SWITCH,
    RES_CASE, RES_DEFAULT, RES_BREAK, RES_CONTINUE, RES_RETURN,
    RES_CLASS, RES_INTERFACE, RES_EXTENDS, RES_IMPLEMENTS,
    RES_IMPORT, RES_PACKAGE, RES_PUBLIC, RES_PRIVATE, RES_PROTECTED,
    RES_STATIC, RES_FINAL, RES_ABSTRACT, RES_SYNCHRONIZED,
    // 标识符
    IDENTIFIER,
    // 其他
    UNKNOWN
}
